-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 09:47:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cc500247_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cc500247_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cc500247_db` DEFAULT CHARACTER SET utf8 ;
USE `cc500247_db` ;

-- -----------------------------------------------------
-- Table `cc500247_db`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc500247_db`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cc500247_db`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc500247_db`.`comuna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comuna_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `cc500247_db`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cc500247_db`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc500247_db`.`domicilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATETIME NOT NULL,
  `comuna_id` INT NOT NULL,
  `nombre_calle` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `sector` VARCHAR(100) NULL,
  `nombre_contacto` VARCHAR(100) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `celular` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_domicilio_comuna1_idx` (`comuna_id` ASC),
  CONSTRAINT `fk_domicilio_comuna1`
    FOREIGN KEY (`comuna_id`)
    REFERENCES `cc500247_db`.`comuna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cc500247_db`.`tipo_mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc500247_db`.`tipo_mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cc500247_db`.`mascota_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc500247_db`.`mascota_domicilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_mascota_id` INT NOT NULL,
  `edad` INT NOT NULL,
  `color` VARCHAR(30) NOT NULL,
  `raza` VARCHAR(30) NOT NULL,
  `esterilizado` INT NOT NULL COMMENT '0: no, 1: si, 2: no aplica',
  `vacunas_al_dia` INT NOT NULL COMMENT '0: no, 1: si, 2: no aplica',
  `domicilio_id` INT NOT NULL,
  INDEX `fk_mascota_domicilio_tipo_mascota1_idx` (`tipo_mascota_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_mascota_domicilio_domicilio1_idx` (`domicilio_id` ASC),
  CONSTRAINT `fk_mascota_domicilio_tipo_mascota1`
    FOREIGN KEY (`tipo_mascota_id`)
    REFERENCES `cc500247_db`.`tipo_mascota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_domicilio_domicilio1`
    FOREIGN KEY (`domicilio_id`)
    REFERENCES `cc500247_db`.`domicilio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cc500247_db`.`foto_mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc500247_db`.`foto_mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta_archivo` VARCHAR(300) NOT NULL,
  `nombre_archivo` VARCHAR(300) NOT NULL,
  `mascota_domicilio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_foto_mascota_domicilio1_idx` (`mascota_domicilio_id` ASC),
  CONSTRAINT `fk_foto_mascota_domicilio1`
    FOREIGN KEY (`mascota_domicilio_id`)
    REFERENCES `cc500247_db`.`mascota_domicilio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
